### ISSUE TITLE
zookeeper.h: No such file or directory

### ISSUE THREAD

**Issue by jerryajay** [dforsyth/donut#1]
I tried running the example code as stated in the README.md . I always keep getting this error no matter how much I try resolving it.
jerry@jerry-OptiPlex-790:~/Desktop/experiment/go$ go install github.com/jerryant/clusters
# launchpad.net/gozk/zookeeper
src/launchpad.net/gozk/zookeeper/zk.go:15:23: fatal error: zookeeper.h: No such file or directory
 #include <zookeeper.h>
 &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;^
compilation terminated.

**Comment by brgnepal** [comment]
I had the same error for  `launchpad.net/gozk` package.
I seems that Ubuntu is missing its required dev package `libzookeeper-mt-dev`

```
sudo apt-get install libzookeeper-mt-dev
```

After installing above, `go get launchpad.net/gozk` works fine.

**Comment by jianfengye** [comment]
if in centos, u can first install cloudera-cdh5.repo, then yum install zookeeper-native

**Comment by stremovskyy** [comment]
On Mac?

**Comment by premal** [comment]
For MACs - https://bugs.launchpad.net/gozk/+bug/1182256
